/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Interfaz.Registro.MenuInscripcion;
import Interfaz.Registro.RegistroClase;
import Interfaz.Registro.RegistroDesercion;
import Interfaz.Registro.RegistroEmpleado;
import Interfaz.Registro.RegistroEvento;
import Interfaz.Estadisticas.RegistroPersonas;
import Interfaz.Registro.RegistroActividad;

/**
 *
 * @author Luis Diego
 */
public class MenuRegistro extends javax.swing.JFrame {

    /**
     * Creates new form MenuRegistro
     */
    public MenuRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Titulo_Registro = new javax.swing.JLabel();
        B_Persona = new javax.swing.JButton();
        B_Evento = new javax.swing.JButton();
        B_Actividad = new javax.swing.JButton();
        B_Clase = new javax.swing.JButton();
        B_Atras = new javax.swing.JButton();
        B_Desercion = new javax.swing.JButton();
        B_Empleado = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 125));
        setMinimumSize(new java.awt.Dimension(380, 320));
        getContentPane().setLayout(null);

        Titulo_Registro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Titulo_Registro.setText("Registro");
        getContentPane().add(Titulo_Registro);
        Titulo_Registro.setBounds(140, 20, 80, 22);

        B_Persona.setText("Persona");
        B_Persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_PersonaActionPerformed(evt);
            }
        });
        getContentPane().add(B_Persona);
        B_Persona.setBounds(60, 80, 100, 44);

        B_Evento.setText("Evento");
        B_Evento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EventoActionPerformed(evt);
            }
        });
        getContentPane().add(B_Evento);
        B_Evento.setBounds(60, 140, 100, 44);

        B_Actividad.setText("Inscripcion");
        B_Actividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ActividadActionPerformed(evt);
            }
        });
        getContentPane().add(B_Actividad);
        B_Actividad.setBounds(60, 200, 100, 44);

        B_Clase.setText("Clase");
        B_Clase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ClaseActionPerformed(evt);
            }
        });
        getContentPane().add(B_Clase);
        B_Clase.setBounds(200, 80, 100, 44);

        B_Atras.setText("Atrás");
        B_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(B_Atras);
        B_Atras.setBounds(10, 10, 70, 23);

        B_Desercion.setText("Deserción");
        B_Desercion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_DesercionActionPerformed(evt);
            }
        });
        getContentPane().add(B_Desercion);
        B_Desercion.setBounds(200, 200, 100, 44);

        B_Empleado.setText("Empleado");
        B_Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(B_Empleado);
        B_Empleado.setBounds(200, 140, 100, 44);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagen1.png"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 370, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_PersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_PersonaActionPerformed
        // TODO add your handling code here:
        dispose();
        new RegistroPersonas().setVisible(true);
    }//GEN-LAST:event_B_PersonaActionPerformed

    private void B_ClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ClaseActionPerformed
        // TODO add your handling code here:
        new RegistroClase().setVisible(true);
        dispose();
    }//GEN-LAST:event_B_ClaseActionPerformed

    private void B_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AtrasActionPerformed
        // TODO add your handling code here:
        dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_B_AtrasActionPerformed

    private void B_EventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EventoActionPerformed
        // TODO add your handling code here:
        dispose();
        new RegistroEvento().setVisible(true);
    }//GEN-LAST:event_B_EventoActionPerformed

    private void B_ActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ActividadActionPerformed
        // TODO add your handling code here:
        dispose();
        new MenuInscripcion().setVisible(true);
    }//GEN-LAST:event_B_ActividadActionPerformed

    private void B_EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EmpleadoActionPerformed
        // TODO add your handling code here:
        dispose();
        new RegistroEmpleado().setVisible(true);
    }//GEN-LAST:event_B_EmpleadoActionPerformed

    private void B_DesercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_DesercionActionPerformed
        // TODO add your handling code here:
        dispose();
        new RegistroDesercion().setVisible(true);
    }//GEN-LAST:event_B_DesercionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Actividad;
    private javax.swing.JButton B_Atras;
    private javax.swing.JButton B_Clase;
    private javax.swing.JButton B_Desercion;
    private javax.swing.JButton B_Empleado;
    private javax.swing.JButton B_Evento;
    private javax.swing.JButton B_Persona;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Titulo_Registro;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
