/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Luis Diego
 */
public class RegistroEvento extends javax.swing.JFrame {

    /**
     * Creates new form RegistroCurso
     */
    public RegistroEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CB_Tipo = new javax.swing.JComboBox<String>();
        L_Tipo = new javax.swing.JLabel();
        CB_Fecha = new javax.swing.JComboBox<String>();
        CB_Hora = new javax.swing.JComboBox<String>();
        L_Fecha = new javax.swing.JLabel();
        L_Hora = new javax.swing.JLabel();
        B_Registrar = new javax.swing.JButton();
        B_Atras = new javax.swing.JButton();
        Titulo_Registro_de_Evento = new javax.swing.JLabel();
        L_Descripcion = new javax.swing.JLabel();
        SP_Descripcion = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 125));
        setMinimumSize(new java.awt.Dimension(380, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        CB_Tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre" }));
        CB_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_TipoActionPerformed(evt);
            }
        });
        getContentPane().add(CB_Tipo);
        CB_Tipo.setBounds(100, 70, 164, 30);

        L_Tipo.setText("Tipo:");
        getContentPane().add(L_Tipo);
        L_Tipo.setBounds(40, 70, 47, 30);

        CB_Fecha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "dd/mm/aaaa" }));
        getContentPane().add(CB_Fecha);
        CB_Fecha.setBounds(100, 110, 146, 30);

        CB_Hora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7:30 a 9:30" }));
        CB_Hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_HoraActionPerformed(evt);
            }
        });
        getContentPane().add(CB_Hora);
        CB_Hora.setBounds(100, 150, 135, 30);

        L_Fecha.setText("Fecha:");
        getContentPane().add(L_Fecha);
        L_Fecha.setBounds(40, 110, 58, 30);

        L_Hora.setText("Hora: ");
        getContentPane().add(L_Hora);
        L_Hora.setBounds(40, 150, 58, 30);

        B_Registrar.setText("Registrar");
        B_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(B_Registrar);
        B_Registrar.setBounds(260, 270, 90, 30);

        B_Atras.setText("Atrás");
        B_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(B_Atras);
        B_Atras.setBounds(10, 10, 70, 23);

        Titulo_Registro_de_Evento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Titulo_Registro_de_Evento.setText("Registro de Evento");
        getContentPane().add(Titulo_Registro_de_Evento);
        Titulo_Registro_de_Evento.setBounds(100, 20, 160, 22);

        L_Descripcion.setText("Descripción:");
        getContentPane().add(L_Descripcion);
        L_Descripcion.setBounds(40, 190, 90, 14);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        SP_Descripcion.setViewportView(jTextArea1);

        getContentPane().add(SP_Descripcion);
        SP_Descripcion.setBounds(40, 210, 210, 60);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagen1.png"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 370, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CB_HoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_HoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_HoraActionPerformed

    private void B_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_RegistrarActionPerformed

    private void B_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AtrasActionPerformed
        // TODO add your handling code here:
        dispose();
        new MenuRegistro().setVisible(true);
    }//GEN-LAST:event_B_AtrasActionPerformed

    private void CB_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_TipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Atras;
    private javax.swing.JButton B_Registrar;
    private javax.swing.JComboBox<String> CB_Fecha;
    private javax.swing.JComboBox<String> CB_Hora;
    private javax.swing.JComboBox<String> CB_Tipo;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel L_Descripcion;
    private javax.swing.JLabel L_Fecha;
    private javax.swing.JLabel L_Hora;
    private javax.swing.JLabel L_Tipo;
    private javax.swing.JScrollPane SP_Descripcion;
    private javax.swing.JLabel Titulo_Registro_de_Evento;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
