/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Luis Diego
 */
public class RegistroCurso extends javax.swing.JFrame {

    /**
     * Creates new form RegistroCurso
     */
    public RegistroCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CB_Curso = new javax.swing.JComboBox<String>();
        L_Curso = new javax.swing.JLabel();
        CB_Mercado = new javax.swing.JComboBox<String>();
        CB_Horario = new javax.swing.JComboBox<String>();
        TF_Costo = new javax.swing.JFormattedTextField();
        L_Costo = new javax.swing.JLabel();
        L_Mercado = new javax.swing.JLabel();
        L_Horario = new javax.swing.JLabel();
        B_Registrar = new javax.swing.JButton();
        B_Atras = new javax.swing.JButton();
        Titulo_Registro_de_Curso = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 125));
        setMinimumSize(new java.awt.Dimension(380, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        CB_Curso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre" }));
        getContentPane().add(CB_Curso);
        CB_Curso.setBounds(130, 70, 164, 28);

        L_Curso.setText("Curso: ");
        getContentPane().add(L_Curso);
        L_Curso.setBounds(70, 70, 47, 28);

        CB_Mercado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Adultos" }));
        getContentPane().add(CB_Mercado);
        CB_Mercado.setBounds(130, 120, 146, 31);

        CB_Horario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7:30 a 9:30" }));
        CB_Horario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_HorarioActionPerformed(evt);
            }
        });
        getContentPane().add(CB_Horario);
        CB_Horario.setBounds(130, 170, 135, 30);
        getContentPane().add(TF_Costo);
        TF_Costo.setBounds(130, 220, 135, 30);

        L_Costo.setText("Costo: ");
        getContentPane().add(L_Costo);
        L_Costo.setBounds(70, 220, 58, 28);

        L_Mercado.setText("Mercado: ");
        getContentPane().add(L_Mercado);
        L_Mercado.setBounds(70, 120, 58, 28);

        L_Horario.setText("Horario: ");
        getContentPane().add(L_Horario);
        L_Horario.setBounds(70, 170, 58, 28);

        B_Registrar.setText("Registrar");
        B_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(B_Registrar);
        B_Registrar.setBounds(250, 270, 100, 30);

        B_Atras.setText("Atrás");
        B_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(B_Atras);
        B_Atras.setBounds(10, 10, 70, 23);

        Titulo_Registro_de_Curso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Titulo_Registro_de_Curso.setText("Registro de Curso");
        getContentPane().add(Titulo_Registro_de_Curso);
        Titulo_Registro_de_Curso.setBounds(110, 20, 140, 22);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagen1.png"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 370, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CB_HorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_HorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_HorarioActionPerformed

    private void B_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_RegistrarActionPerformed

    private void B_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AtrasActionPerformed
        // TODO add your handling code here:
        dispose();
        new MenuRegistro().setVisible(true);
    }//GEN-LAST:event_B_AtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Atras;
    private javax.swing.JButton B_Registrar;
    private javax.swing.JComboBox<String> CB_Curso;
    private javax.swing.JComboBox<String> CB_Horario;
    private javax.swing.JComboBox<String> CB_Mercado;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel L_Costo;
    private javax.swing.JLabel L_Curso;
    private javax.swing.JLabel L_Horario;
    private javax.swing.JLabel L_Mercado;
    private javax.swing.JFormattedTextField TF_Costo;
    private javax.swing.JLabel Titulo_Registro_de_Curso;
    // End of variables declaration//GEN-END:variables
}
