/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Luis Diego
 */
public class RegistroPuesto extends javax.swing.JFrame {

    /**
     * Creates new form RegistroCurso
     */
    public RegistroPuesto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_Nombre = new javax.swing.JLabel();
        L_Descripcion = new javax.swing.JLabel();
        B_Registrar = new javax.swing.JButton();
        B_Atras = new javax.swing.JButton();
        Titulo_Registro_de_Puesto = new javax.swing.JLabel();
        SP_Descripcion = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        TF_Nombre = new javax.swing.JTextField();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 125));
        setMinimumSize(new java.awt.Dimension(380, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        L_Nombre.setText("Nombre:");
        getContentPane().add(L_Nombre);
        L_Nombre.setBounds(60, 90, 47, 28);

        L_Descripcion.setText("Descripción:");
        getContentPane().add(L_Descripcion);
        L_Descripcion.setBounds(60, 150, 90, 28);

        B_Registrar.setText("Registrar");
        B_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(B_Registrar);
        B_Registrar.setBounds(260, 270, 90, 30);

        B_Atras.setText("Atrás");
        B_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(B_Atras);
        B_Atras.setBounds(10, 10, 70, 23);

        Titulo_Registro_de_Puesto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Titulo_Registro_de_Puesto.setText("Registro de Puesto");
        getContentPane().add(Titulo_Registro_de_Puesto);
        Titulo_Registro_de_Puesto.setBounds(100, 30, 180, 22);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        SP_Descripcion.setViewportView(jTextArea1);

        getContentPane().add(SP_Descripcion);
        SP_Descripcion.setBounds(60, 180, 210, 60);
        getContentPane().add(TF_Nombre);
        TF_Nombre.setBounds(110, 90, 180, 30);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagen1.png"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 370, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_RegistrarActionPerformed

    private void B_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AtrasActionPerformed
        // TODO add your handling code here:
        dispose();
        new MenuRegistro().setVisible(true);
    }//GEN-LAST:event_B_AtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Atras;
    private javax.swing.JButton B_Registrar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel L_Descripcion;
    private javax.swing.JLabel L_Nombre;
    private javax.swing.JScrollPane SP_Descripcion;
    private javax.swing.JTextField TF_Nombre;
    private javax.swing.JLabel Titulo_Registro_de_Puesto;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
